config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :users, only: [:show] do
    resources :tasks, only: [:index]
    get '/tasks/:tag_id', to: 'tasks#show_tasks_tag', as: 'tasks_tag'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  
  belongs_to :user
  has_many :tag_tasks
  has_many :tasks, through: :tag_tasks

  before_validation :valid_name

  private

  def valid_name
    if Tag.where(user_id: current_user.id).map(&:name).include?(self.name)
      errors.add(:tag_name, "Already using the name")
    end
  end
end

app/models/tag_task.rb
class TagTask < ApplicationRecord
  belongs_to :tag
  belongs_to :task

  before_validation :valid_tag_add_task

  private

  def valid_tag_add_task
    if tag_included? || tag_limit?
      errors.add(:tag_name, "It is not possible to add such a tag")
    end
  end

  def tag_limit?
    self.task.tags.count >= 3
  end

  def tag_included?
    self.task.tags.map(&:name).include?(self.tag.name)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :status, presence: true
  validates :level, :inclusion => 0..5, numericality: { only_integer: true }
  enum status: [ :done, :to_do ]

  belongs_to :user
  has_many :tag_tasks
  has_many :tags, through: :tag_tasks

  scope :filter_status, -> (status) { where status: status }
  scope :filter_level, -> (level) { where level: level }
  scope :filter_created_at, -> (created_at) { where('created_at >= ?', created_at) }
  scope :filter_deadline, -> (deadline) { where('deadline <= ?', deadline) }
  scope :filter_tag, -> (tag) { joins(:tags).where("tags.id = ?", tag)}
  scope :filter_deadline_range, -> (deadline_end) { where("deadline >= ? AND ? <= deadline", DateTime.now, deadline_end)}
  scope :order_deadline_level, -> { order('deadline DESC', created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tag
  has_many :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  before_action :require_login, :correct_user

  def require_login
    redirect_to not_logged if current_user.nil?
  end

  def current_user
    @current_user ||= User.find(params["user_id"])
  end

  def correct_user
    unless current_user == User.find(params["user_id"])
      redirect_to unauthorized
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = TaskServices::FiltersTasks.new(current_user.id, 
              :deadline_range => DateTime.now + 7.days, 
              :status => "to_do").apply_filters.order_deadline_level
  end

  def show_tasks_tag
    @tasks = Tag.find(params["tag_id"]).tasks.to_a.each{ |task| task.user_id == current_user.id }
    render action: :index
  end
  
  def create
    @task = Task.new(task_params, user_id: current_user.id)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def task_params
    params.fetch(:task, {})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<style>
  table, th, td {
    padding: 5px;
    border: 1px solid black;
  }
</style>
<table>
  <thead>
    <tr>
      <th>Tarea</th>
      <th>Descripción</th>
      <th>Fecha de finalización</th>
      <th>Estado</th>
      <th>Nivel de importancia</th>
      <th>Etiqueta</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.level %></td>
        <td>
        <% unless task.tags.blank? %>
          <% task.tags.each do |tag| %>
            <%= link_to tag.name, user_tasks_tag_path(tag_id: tag.id) %>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>